name: Simple 3 Job Workflow

on:
  push:
    branches: [main]

jobs:

  # -------------------
  # 1️⃣ Job One
  # -------------------
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello from Job 1
        run: echo "This is Job One"


  # -------------------
  # 2️⃣ Job Two (depends on Job One)
  # -------------------
  job_two:
    runs-on: ubuntu-latest
    needs: job_one
    steps:
      - name: Say hello from Job 2
        run: echo "This is Job Two"


  # -------------------
  # 3️⃣ Job Three (depends on Job Two)
  # -------------------
  job_three:
    runs-on: ubuntu-latest
    needs: job_two
    steps:
      - name: Say hello from Job 3
        run: echo "This is Job Three"
